replicas: 1

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "200m"
    memory: "512Mi"

# ربط Filebeat بالـ Elasticsearch
elasticsearch:
  hosts: ["http://elasticsearch-master.efk.svc.cluster.local:9200"]

# أي ملفات عايزة تتبعيها
filebeat.inputs:
  - type: log
    paths:
      - /var/log/*.log

# Optional: إذا عايزة تخلي Filebeat يشتغل كـ DaemonSet
# daemonset:
#   enabled: true

